### ISSUE TITLE
Wrong encodings for cosines

### ISSUE THREAD

**Issue by YannDubs** [kaushalshetty/Positional-Encoding#1]
Why are you using `position_enc[1:, 1::2] = np.cos(position_enc[1:, 1::2])` instead of `position_enc[:, 1::2] = np.cos(position_enc[:, 1::2])` (i.e don't start at 1)? Currently you are saying thate cosines start at 0 instead of 1.

Plot of current code:
<img width="920" alt="screenshot 2019-01-17 at 23 28 15" src="https://user-images.githubusercontent.com/24327668/51355833-335fe680-1ab0-11e9-8442-57e4523757a7.png">

Instead of the correct:

<img width="916" alt="screenshot 2019-01-17 at 23 33 41" src="https://user-images.githubusercontent.com/24327668/51355878-60ac9480-1ab0-11e9-9f03-49e443a88ded.png">

**Comment by kaushalshetty** [comment]
@YannDubs Yes. You are right if there is no padding token in the beginning. I assume pad token as the 0th dim which is initialised with 0. Applying cosine or sin on padding token did not make sense to me.
